### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by elohmrow** [pvande/Template-Mustache#20]
rakudo-star-2015.07/install/bin/perl6-m --target=mbc --output=rakudo-star-2015.07/install/share/perl6/lib/Template/Mustache.pm.moarvm rakudo-star-2015.07/install/share/perl6/lib/Template/Mustache.pm
Saw 1 occurrence of deprecated code.
================================================================================
$*PROGRAM_NAME seen at:
  rakudo-star-2015.07/install/share/perl6/lib/Template/Mustache.pm, line 184
Deprecated since v2015.6, will be removed with release v2015.9!
Please use $*PROGRAM-NAME instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!

Please note that *ALL* deprecated features will be removed at the RC-0 release
(expected September 2015).

**Comment by rjbs** [comment]
This repository is for a Perl 5 library.  I don't know where the Perl 6 code lives, but I don't think it's here.

**Comment by rjbs** [comment]
It has been suggested that you wanted https://github.com/softmoth/p6-Template-Mustache/

**Comment by elohmrow** [comment]
sorry - that's what i thought i had :)
