### ISSUE TITLE
Doesn't install because of Test::Mini 1.1.3

### ISSUE THREAD

**Issue by dolmen** [pvande/Template-Mustache#36]
Template::Mustache fails to install on perl 5.20.1 because Test::Mini 1.1.3 fails to install.
See pvande/Test-Mini#18.

Workaround: install `NEILB/Test-Mini-1.1.3_01.tar.gz`.

**Comment by yanick** [comment]
I pushed changes that remove the Test::Mini dependency. That will take care of that.
