### ISSUE TITLE
Enable Travis for the repo

### ISSUE THREAD

**Issue by yanick** [pvande/Template-Mustache#37]
A Travis config has been added to the repo, and the web service can be activated. Since I don't have permissions to edit the settings of the repo, this one is yours, @pvande.

**Comment by pvande** [comment]
Done.  Thanks for the heads up, @yanick!

**Comment by yanick** [comment]
My pleasure. :-)

**Comment by pvande** [comment]
By the way, if you'd like me to transfer ownership of the repository to you, just let me know.  I haven't worked in Perl since this repo went dormant, and it's not likely something I'm going to pick up again...

**Comment by yanick** [comment]
Sure, I'd be honored. :-)

**Comment by pvande** [comment]
Hmm...

> Before you transfer a repository, keep these things in mind:

> * When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete.
> * The target account must not have a repository with the same name, or a fork in the same network.
> * The original owner of the repository is added as a collaborator on the transferred repository. Other collaborators to the transferred repository remain intact.
> * Private forks can't be transferred.

It looks like I can't transfer ownership so long as you've still got a fork on your account.

**Comment by yanick** [comment]
I deleted my fork. I'm ready. :-)
